# services:
#   nestjs:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '3000:3000'
#     depends_on:
#       - postgres
#     environment:
#       DATABASE_URL: postgres://admin:secret@postgres:5432/fitproDB

#   postgres:
#     image: postgres:15
#     env_file:
#       - .env
#     ports:
#       - '5432:5432'
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:


