# services:
#   nest-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     environment:
#       DB_HOST: db
#       DB_PORT: 5432
#       DB_USERNAME: admin
#       DB_PASSWORD: secret123
#       DB_NAME: fitproDB
#     volumes:
#       - .:/app
#     command: npm run start:prod

#   db:
#     image: postgres:14
#     container_name: gym-postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: fitproDB
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: secret123
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin-gym
#     ports:
#       - "5050:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@example.com
#       PGADMIN_DEFAULT_PASSWORD: admin123
#     depends_on:
#       - db

# volumes:
#   postgres_data:



